Repository TaloDev/frontend, pull requests merged in 2025-03, with the labels that each got.

#341 Channel management modal + filter players by channel
  src/api/createChannel.ts
  src/api/deleteChannel.ts
  src/api/updateChannel.ts
  src/api/useChannels.ts
  src/components/Modal.tsx
  src/components/PlayerAliases.tsx
  src/components/Select.tsx
  src/entities/gameChannels.ts
  src/modals/ChannelDetails.tsx
  src/modals/LeaderboardDetails.tsx
  src/pages/Channels.tsx
  src/pages/Groups.tsx
  src/pages/LeaderboardEntries.tsx
  src/pages/Organisation.tsx
  src/pages/Stats.tsx
  src/utils/canPerformAction.ts
Labels: enhancement

#345 Release 0.47.0
  README.md
  package-lock.json
  package.json
  src/api/createChannel.ts
  src/api/deleteChannel.ts
  src/api/updateChannel.ts
  src/api/useChannels.ts
  src/components/Modal.tsx
  src/components/PlayerAliases.tsx
  src/components/Select.tsx
  src/entities/gameChannels.ts
  src/modals/ChannelDetails.tsx
  src/modals/LeaderboardDetails.tsx
  src/pages/Channels.tsx
  src/pages/Groups.tsx
  src/pages/LeaderboardEntries.tsx
  src/pages/Organisation.tsx
  src/pages/Stats.tsx
  src/utils/canPerformAction.ts
Labels: release

#342 add bulk config import
  src/components/PropsEditor.tsx
  src/components/TextInput.tsx
Labels: enhancement

#347 Upgrade to Vite 6
  cypress/e2e/pages/Register.spec.cy.js
  package-lock.json
  package.json
  src/components/PropsEditor.tsx
  vite.config.ts
Labels: enhancement

#348 Use caddy instead of nginx for Docker image
  .env.production
  Dockerfile
  config/Caddyfile
  config/entrypoint.sh
  config/nginx.conf
Labels: enhancement

#349 Release 0.48.0
  .env.production
  Dockerfile
  config/Caddyfile
  config/entrypoint.sh
  config/nginx.conf
  cypress/e2e/pages/Register.spec.cy.js
  package-lock.json
  package.json
  src/api/usePricingPlanUsage.ts
  src/components/GameSwitcher.tsx
  src/components/HeadlineStat.tsx
  src/components/Modal.tsx
  src/components/PropsEditor.tsx
  src/components/TextInput.tsx
  src/components/UsageWarningBanner.tsx
  src/components/billing/PricingPlanTile.tsx
  src/pages/AcceptInvite.tsx
  src/pages/ConfirmPassword.tsx
  src/pages/Demo.tsx
  src/pages/ForgotPassword.tsx
  src/pages/Login.tsx
  src/pages/NotFound.tsx
  src/pages/RecoverAccount.tsx
  src/pages/ResetPassword.tsx
  src/pages/Verify2FA.tsx
  src/pages/__tests__/PlayerProps.test.tsx
  src/utils/usePortal.ts
  vite.config.ts
Labels: release

#350 Release 0.48.0
  package-lock.json
  package.json
Labels: release

#352 Use protected flag to prevent non-env-vars from being overwritten
  .env.production
  config/entrypoint.sh
  src/index.tsx
  src/utils/canPerformAction.ts
  src/utils/canViewPage.ts
Labels: fix

#353 Release 0.48.2
  .env.production
  config/entrypoint.sh
  package-lock.json
  package.json
  src/index.tsx
  src/utils/canPerformAction.ts
  src/utils/canViewPage.ts
Labels: release
